name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for trusted publishing and npm provenance

    steps:
    - uses: actions/checkout@v5

    # because npm 10.8.2 (default) doesn't work with trusted publishing, 11.6.2 works
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    - name: Install npm dependencies
      run: yarn install

    - name: Build library package
      run: yarn build:lib --configuration=production

    - name: Copy readme and license files
      run: yarn build:copy-files

    - name: Run library tests
      run: yarn test:lib --configuration=ci

    - name: Run demo app tests
      run: yarn test:demo --configuration=ci

    - name: Show package.json
      run: cat dist/ngx-sweetalert2/package.json

    - name: Build library package for publishing
      run: yarn build:lib --configuration production

    - name: Run automated release process with semantic-release
      if: github.event_name == 'push' && contains(github.ref, 'main')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: yarn semantic-release
