name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install npm dependencies
      run: yarn install

    - name: Build library package
      run: yarn build:lib --configuration=production

    - name: Copy readme and license files
      run: yarn build:copy-files

    - name: Run library tests
      run: yarn test:lib --configuration=ci

    - name: Run demo app tests
      run: yarn test:demo --configuration=ci

    - name: Show package.json
      run: cat dist/ngx-sweetalert2/package.json

    - name: Build library package for publishing
      run: yarn build:lib --configuration production

    - name: Run automated release process with semantic-release
      if: github.event_name == 'push' && contains(github.ref, 'main')
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: yarn semantic-release
